### ISSUE TITLE
Error: Cannot find module './dist/index'

### ISSUE THREAD

**Issue by DKB0512** [adrian-ub/nest-deta#1]
He estado probando su método para alojar mi aplicación nestJs en detalle, pero recibo el error:

`Error: Cannot find module './dist/index'`

Qué estoy haciendo :
-> Copie y pegue el código de índice según su blog.
-> Ejecuté "npm run build" para construir mi proyecto
-> Creado nuevo proyecto deta
-> deta desplegar a ese micro.

Pero incluso después de hacer todo eso, cada vez que intento ejecutar la aplicación usando la micro URL detallada, aparece el error No encontrado en los registros detallados.

**Comment by adrian-ub** [comment]
Hola @DKB0512, gracias por seguir las instrucciones en mi blog

- ¿Tienes un repo de ejemplo? 
- ¿Qué versión de Nest estás usando?

Y, ¿agregaste el archivo en la ruta `src/index.ts`?

```ts
import { NestFactory } from '@nestjs/core';
import { ExpressAdapter } from '@nestjs/platform-express';
import { AppModule } from './app.module';

const createNestServer = async (expressInstance) => {
  const app = await NestFactory.create(
    AppModule,
    new ExpressAdapter(expressInstance),
  );
  return app.init();
};

export default createNestServer;
```
